### ISSUE TITLE
Anomaly when unwanted data is in a folder

### ISSUE THREAD

**Issue by jene8774** [Lite3DP/Lite3DP-Gen-2#8]
If there are non-image data in the folder, Lite3DP seems to be unable to recognize it and, force the touchscreen image to be displayed on the UV panel.

![pic10c](https://github.com/user-attachments/assets/f7bf8895-1ae5-4e6f-8253-e0ba222f94d5)

The chitubox contains data other than the mask image in the extracted zip file.
This may be the cause of the anomaly.

![10pic](https://github.com/user-attachments/assets/cf409dc6-a86a-4e8b-8ddd-f5a41c08f661)
After deleting unnecessary data, the system worked properly.

**Comment by Lite3DP** [comment]
Hey, thanks for this discovery. The application counts all files in the folder, since depending on the Slicer and its version it may include some additional files like preview images, gcode, a readme file, etc. However, there was supposed to be a black screen before each image, so the last layers corresponding to these additional files that are not slice images are not printed at all. Evidently at some point this black screen was removed from the code without realizing it.
Solution added to [Troubleshooting guide](https://github.com/Lite3DP/Lite3DP-Gen-2/tree/main/Troubleshooting).
